### ISSUE TITLE
boot.host_shutdown_action not processed properly

### ISSUE THREAD

**Issue by st0nie** [cmspam/incus-docker#13]
https://linuxcontainers.org/incus/docs/main/reference/instance_options/

As above, if incus is installed directly in the host, then the system shutdown will automatically stop these incus instances, but if incus is installed with docker, the system shutdown will first stop the image, and then it will call start.sh to stop incusd, but the `incus admin shutdown` will not have any effect on these instances that need to be stopped. stateful-stop, which will result in a loss of state for the instance.

A better solution might be:
Before incus admin shutdown invoke the
`incus list -f json | jq '. [] | select(.expanded_config."boot.host_shutdown_action" == "stateful-stop" and .status == "Running" ) | .name'`
Find all containers that need a stateful shutdown and store them in volume
Afterwards, just start these containers at boot time using `start.sh`

**Comment by st0nie** [comment]
I now find the workaround:
/etc/systemd/system/incus.service:
```service
[Unit]
Description=incus-docker

[Service]
Type=oneshot
WorkingDirectory=/root/docker/incus
ExecStart=/usr/bin/docker compose up -d
ExecStart=/root/docker/incus/start-post.sh
ExecStop=/root/docker/incus/stop-pre.sh
ExecStop=/usr/bin/docker compose down
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```
docker-compose.yml:
```yml
services:
  incus:
    image: ghcr.io/cmspam/incus-docker:latest
    container_name: incus
    privileged: true
    environment:
      - SETIPTABLES=true
    network_mode: host
    pid: host
    cgroup: host
    volumes:
      - /dev:/dev
      - /var/lib/incus:/var/lib/incus
      - /lib/modules:/lib/modules:ro
```
start-post.sh:
```sh
#!/bin/bash
incus admin waitready
file="/var/lib/incus/stateful"

if [[ ! -f "$file" ]]; then
    exit 1
fi

while IFS= read -r line; do
    incus start "$line"
done < "$file"

rm -f $file
```
stop-pre.sh:
```sh
#!/bin/bash
instances=$(incus list -f json | jq -r '. [] | select(.expanded_config."boot.host_shutdown_action" == "stateful-stop" and .status == "Running" ) | .name')
echo "$instances" | while IFS= read -r line; do
    incus stop "$line" --stateful
    echo "$line" >> /var/lib/incus/stateful
done

incus admin shutdown
```

After that, we use systemd to manage the containers, so that when shutting down, systemd automatically stops the service, thus preserving the state of the containers correctly.
